[package]
name = "flashlight"
version = "0.0.1"
edition = "2021"
publish = false
license-file = "LICENSE"
readme = "README.md"

[lib]
name = "flashlight"
crate-type = ["cdylib", "rlib"]

[dependencies]
